---
apiVersion: v2
name: blazar-reservation-splitter
description: A Helm chart for Blazar Reservation Splitter
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - openstack
  - blazar
  - ceilometer
  - gnocchi
  - metrics
  - reservations
maintainers:
  - name: Rackspace Technology
home: https://github.com/rackerlabs/genestack
sources:
  - https://github.com/rackerlabs/genestack-images
dependencies:
  - name: helm-toolkit
    repository: file://../helm-toolkit
    version: ">= 0.1.0"
